# Generated by Django 3.1.2 on 2020-12-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sal',
            new_name='score',
        ),
    ]
